
 

name: Deploy Jar

on:
  [push]
env:
  JAVA_VERSION: '1.8'               

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn package 
      
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "./"
        REMOTE_HOST: "44.211.151.74"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/tmp"
        run: cd /home/ubuntu/tmp && sudo cp /webapp/target/webapp.war /opt/tomcat/webapps/webapp
