name: Deploy Jar

on:
  [push]
env:
  JAVA_VERSION: '1.6'               

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.6
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn clean install && mvn package
